<a href="https://colab.research.google.com/github/tjohnson-scottlogic/aoc2025/blob/main/day09/day09.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [71]:
"""

for each dot
  if red
    for each column from the right
      for each red
        calculate rectangle

"""

'\n\nfor each dot\n  if red\n    for each column from the right\n      for each red\n        calculate rectangle\n\n'

In [72]:
import numpy as np

In [73]:
RED = 1
#FILENAME = "test.txt"
#FILENAME = "sample.txt"
FILENAME = "input.txt"
#WIDTH = 6
#WIDTH = 14
WIDTH = 100000
#DEPTH = 6
#DEPTH = 9
DEPTH = 100000

current_rectangle_area = 0
largest_rectangle_area = 0

In [74]:
# Load floor pattern into array (each location is across then down)
floor_pattern = np.zeros((DEPTH,WIDTH))
data = open(FILENAME, 'r')
for line in data.readlines():
  location = line.split(',')
  floor_pattern[int(location[1]), int(location[0])] = RED
print(floor_pattern)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [75]:
"""

for each dot
  if red
    for each column from the right
      for each red
        calculate rectangle

"""

for i in range(0,DEPTH):
  for j in range(0,WIDTH):
    #print(f"i = {i}, j = {j}, tile is {floor_pattern[i,j]}")
    if (floor_pattern[i,j] == RED):
      for k in range(DEPTH-1,i-1,-1):
        for l in range(WIDTH-1,j-1,-1):
          if (floor_pattern[k,l] == RED):
            #print(f"Found RED at k = {k}, l = {l}")
            current_rectangle_area = ((k-i)+1) * ((l-j)+1)
            #print(f"current_rectangle_area = {current_rectangle_area}")
            if (current_rectangle_area > largest_rectangle_area):
              largest_rectangle_area = current_rectangle_area

print(f"largest_rectangle_area = {largest_rectangle_area}")

KeyboardInterrupt: 